version: '3.8'

services:  

  # redis:
  #   image: "redis:latest"
  #   ports:
  #     - 6379:6379
  
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  # rabbitmq:
  #   hostname: rabbitmq
  #   image: rabbitmq:latest
  #   env_file:
  #     - .env

  # worker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: celery --app=automappa.tasks.queue worker --loglevel INFO
  #   volumes:
  #     - ./automappa:/usr/src/app
  #   links:
  #     - rabbitmq
  #     - redis
  #   depends_on:
  #     - rabbitmq
  #     - redis
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: automappa --debug --port 8050
    # env_file:
    #   - .env
    volumes:
      # /usr/src/app is location of install in Dockerfile
      - .:/usr/src/app
    ports:
      - 8050:8050
    depends_on:
      - db
      # - rabbitmq
      # - redis

volumes:
  pg_data:
    driver: local