version: '3'

services:  

  redis:
    image: redis:latest
    hostname: redis

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass

  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: automappa
    volumes:
      - .:/automappa 
    ports:
      - "5000:5000"
    links:
      - rabbitmq
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery --app=automappa.tasks.queue worker --loglevel INFO
    volumes:
      - .:/automappa
    links:
      - rabbitmq
      - redis
    depends_on:
      - rabbitmq
      - redis
