version: '3'

services:  

  # redis:
  #   image: redis:latest
  #   hostname: redis
  
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  # rabbitmq:
  #   hostname: rabbitmq
  #   image: rabbitmq:latest
  #   env_file:
  #     - .env
  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: automappa
    volumes:
      - .:/automappa 
    ports:
      - "5000:5000"
    links:
      # - rabbitmq
      # - redis
      - postgres

  # worker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: celery --app=automappa.tasks.queue worker --loglevel INFO
  #   volumes:
  #     - .:/automappa
  #   links:
  #     - rabbitmq
  #     - redis
  #   depends_on:
  #     - rabbitmq
  #     - redis
