version: '3.8'

services:  

  
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  # rabbitmq:
  #   image: rabbitmq:latest
  # celery:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: celery --app=automappa.tasks.queue worker --loglevel INFO
  #   volumes:
  #     - .:/usr/src/app
  # flower:
  #   image: "mher/flower:latest"
  #   ports:
  #     - 1234:1234
  # redis:
  #   image: "redis:latest"
  #   ports:
  #     - 6379:6379
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # command: automappa --debug --port 8050
    # This command allows live-reloading for dev
    # Not sure which is more appropriate for production :shrug:
    command: python -m automappa.index --debug --port 8050
    volumes:
      # /usr/src/app is location of install in Dockerfile
      - .:/usr/src/app
    ports:
      - 8050:8050
    depends_on:
      - db
      # - rabbitmq
      # - celery
      # - redis

volumes:
  pg_data:
    driver: local