name: automappa
channels:
  - plotly
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - autometa
  - flask
  - celery[redis]
  - dash
  - dash-bootstrap-components
  - dash-daq
  - dash-extensions
  - msgpack-python
  - numpy
  - pandas
  - plotly
<<<<<<< Updated upstream
  - python-dotenv
=======
  - pip
  - pip:
    - geom-median
>>>>>>> Stashed changes
