name: automappa
channels:
  - conda-forge
  - bioconda
  - plotly
  - defaults
dependencies:
  - autometa
  - dash
  - dash-bootstrap-components
  - dash-daq
  - dash-extensions
  - flask
  - flower
  - msgpack-python
  - numpy
  - pandas
  - plotly
  - psycopg2
  - python-dotenv
  - pydantic
  - sqlalchemy
  - pip
  - pip:
    - celery[redis]
    - geom-median
    - dash-uploader
