name: automappa
channels:
  - conda-forge
  - bioconda
  - plotly
  - defaults
dependencies:
  - autometa
  - dash==2.10.2
  - dash-bootstrap-components
  - dash_cytoscape==0.2.0
  - flask
  - flower
  - msgpack-python
  - numpy==1.20.0
  - pandas
  - plotly
  - psycopg2
  - python-dotenv
  - python==3.9.*
  - pydantic>=1.8.2,<2.0.0
  - scipy
  - scikit-learn==0.24
  - sqlalchemy==1.4.41
  - sqlmodel==0.0.8
  - pip
  - pip:
    - dash-extensions==1.*
    - dash-mantine-components==0.12
    - dash-ag-grid>=2.2
    - dash-iconify
    - celery[redis]
    - geom-median
    - dash-uploader==0.6
