name: automappa
channels:
  - conda-forge
  - bioconda
  - plotly
  - defaults
dependencies:
  - autometa
  - dash==2.10.2
  - dash-bootstrap-components
  - dash_cytoscape==0.2.0
  - dash-daq
  - dash-labs
  - flask
  - flower
  - msgpack-python
  - numpy
  - pandas
  - plotly
  - psycopg2
  - python-dotenv
  - python==3.9.*
  - pydantic
  - scipy==1.8.*
  - scikit-learn==0.24
  - sqlalchemy>=1.4
  - pip
  - pip:
    - dash-extensions==1.*
    - dash-mantine-components==0.12
    - dash-iconify
    - celery[redis]
    - geom-median
    - dash-uploader