name: automappa
channels:
  - plotly
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - autometa
  - flask
  - celery[redis]
  - dash
  - dash-bootstrap-components
  - dash-daq
  - dash-extensions==0.0.71
  - msgpack-python
  - numpy
  - pandas
  - plotly
