name: docker CI/CD

on:
  release:
    types: [published]
  push:
    # Only construct the image if changes affect the image...
    paths:
      - "automappa/**"
      - "docker/**"
      - "Dockerfile"
      - "environment.yml"
      - "Makefile"
      - "setup.py"
    branches:
      - main
  pull_request:
    paths:
      - "automappa/**"
      - "docker/**"
      - "Dockerfile"
      - "environment.yml"
      - "Makefile"
      - "setup.py"
    branches:
      - main

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: evanrees/automappa
          tags: |
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=raw,value={{branch}}
            type=semver,pattern={{version}}
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        id: automappa_docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}